name: 'SWM: Deploy to Azure'

on:
  push:
    branches:
      - main

jobs:
  build-test:
    name: 'Build and Test'

    runs-on: ubuntu-latest

    steps:
      - name: Set enviroment variables
        shell: bash
        run: |
          echo "FUNCTION_APP_PATH=${{ $GITHUB_WORKSPACE }}/api" >> $GITHUB_ENV
    
      - name: Check enviroment variables
        shell: bash
        run: |
          echo "FUNCTION_APP_PATH"

      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Setup .Net SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'

      - name: Restore NuGet packages
        shell: bash
        run: |
          dotnet restore .

      - name: Build FunctionApp
        shell: bash
        run: |
          dotnet build . -c Release

      - name: Test FunctionApp
        shell: bash
        run: |
          dotnet test . -c Release

      - name: Create FunctionApp artifact
        shell: bash
        run: |
          pushd "${{ env.FUNCTION_APP_PATH }}"
          dotnet publish . -c Release -o published
          popd

      - name: Upload FunctionApp artifact
        uses: actions/upload-artifact@v2
        with:
          name: apiapp
          path: ${{ env.FUNCTION_APP_PATH }}/published